[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_twitter = "2AJsjtSrGowm3ofSnFCUvfRZqng4DXdBXE4KHmj2jgSC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
